<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1vvhbYR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1vvhbYR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1vvhbYR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1vvhbYR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1vvhbYR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1vvhbYR',
    'container.build_id' => 'cfa279a9',
    'container.build_time' => 1579165057,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1vvhbYR');
